export const ACTION_TYPES = {
  SETGROUPS: '@@SET-GROUPS',
  FETCHGROUPS: '@@SET-FETCHGROUPS',
  SETRECENTS: '@@SET-RECENTS',
  FETCHRECENTS: '@@SET-FETCHRECENTS',
  SETFRIENDS: '@@SET-FRIENDS',
  FETCHFRIENDS: '@@SET-FETCHFRIENDS',
  SETRECENTCALLS: '@@SET-RECENTCALLS',
  SETSEARCHRESULT: '@@SET-SEARCHRESULT',
  SET_CHAT_USER: '@@SET-CHAT-USER',
  ADD_NEW_MESSAGE: '@@ADD-NEW-MESSAGE'
}