export const ACTION_TYPES = {
  SETGROUPS: '@@SET-GROUPS',
  SETRECENTS: '@@SET-RECENTS',
  SETFRIENDS: '@@SET-FRIENDS',
  SETRECENTCALLS: '@@SET-RECENTCALLS',
  SETSEARCHRESULT: '@@SET-SEARCHRESULT',
  SET_CHAT_USER: '@@SET-CHAT-USER',
  ADD_NEW_MESSAGE: '@@ADD-NEW-MESSAGE'
}